version: '3.8'

services:
    postgresql:
        volumes:
            - ./postgresql/database:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    directus:
        ports:
            - "8055:8055"
        environment:
            CORS_ENABLED: "true"
            CORS_ORIGIN: "http://localhost:3000"

    web:
        deploy:
            replicas: 0

networks:
    directus:
        external: false

volumes:
    postgresql:
        name: "postgresql"
        external: false
