version: '3.8'

services:
    postgresql:
        container_name: cafet_postgresql
        image: postgres:14.2-alpine
        volumes:
            - postgresql:/var/lib/postgresql/data
        networks:
            - cafet_internal
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: 'directus'

    redis:
        container_name: cafet_redis
        image: redis:alpine
        networks:
            - cafet_internal

    directus:
        container_name: cafet_directus
        image: directus/directus:9.11.0
        hostname: cafet-directus
        volumes:
            - directus_uploads:/directus/uploads
            - ./directus/schema:/directus/schema
            - ./directus/extensions:/directus/extensions
        networks:
            - cafet_web
            - cafet_internal
        depends_on:
            - redis
            - postgresql
        environment:
            KEY: "${DIRECTUS_KEY}"
            SECRET: "${DIRECTUS_SECRET}"

            DB_CLIENT: 'pg'
            DB_HOST: 'postgresql'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: "${POSTGRES_USER}"
            DB_PASSWORD: "${POSTGRES_PASSWORD}"

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            CACHE_REDIS: 'redis://redis:6379'

            ADMIN_EMAIL: "${ADMIN_EMAIL}"
            ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

            PUBLIC_URL: "${PUBLIC_URL}"

            CORS_ENABLED: "true"
            CORS_ORIGIN: "${WEB_CORS_ORIGIN}"

    web:
        container_name: cafet_web
        image: cefadrom/cesi-caisse-cafet:latest
        hostname: cafet-web
        build:
            context: ./web
            args:
                VITE_API_ENDPOINT: "${VITE_API_ENDPOINT}"
        networks:
            - cafet_web
        depends_on:
            - directus


networks:
    cafet_web:
        name: "cafet_web"
        external: true
    cafet_internal:
        name: "cafet_internal"
        external: false

volumes:
    postgresql:
        name: "cafet_postgresql"
        external: true
    directus_uploads:
        name: "cafet_directus_uploads"
        external: true
