version: '3.8'

services:
    postgresql:
        container_name: postgresql
        image: postgres:14.2-alpine
        volumes:
            - postgresql:/var/lib/postgresql/data
            - ./postgresql/dump:/dump
        networks:
            - directus
        environment:
            POSTGRES_USER: "${POSTGRES_USER}"
            POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
            POSTGRES_DB: 'directus'

    redis:
        container_name: redis
        image: redis:alpine
        networks:
            - directus

    directus:
        container_name: directus
        image: directus/directus:latest
        volumes:
            - ./directus/uploads:/directus/uploads
            - ./directus/schema:/directus/schema
            - ./directus/extensions:/directus/extensions
        networks:
            - directus
        depends_on:
            - redis
            - postgresql
        environment:
            KEY: "${DIRECTUS_KEY}"
            SECRET: "${DIRECTUS_SECRET}"

            DB_CLIENT: 'pg'
            DB_HOST: 'postgresql'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: "${POSTGRES_USER}"
            DB_PASSWORD: "${POSTGRES_PASSWORD}"

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            CACHE_REDIS: 'redis://redis:6379'

            ADMIN_EMAIL: "${ADMIN_EMAIL}"
            ADMIN_PASSWORD: "${ADMIN_PASSWORD}"

            PUBLIC_URL: "${PUBLIC_URL}"

networks:
    directus:
        name: "directus"
        external: true

volumes:
    postgresql:
        name: "cafet_postgresql"
        external: true
