version: '3.8'

services:
    postgresql:
        volumes:
            - ./postgresql/database:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    directus:
        ports:
            - "8055:8055"
        volumes:
            - ./directus/uploads:/directus/uploads
        environment:
            CORS_ORIGIN: "*"
            EXTENSIONS_AUTO_RELOAD: "true"
            # Classic watch mode doesn't work with WSL volumes
            CHOKIDAR_USEPOLLING: "true"
            CHOKIDAR_INTERVAL: 1000

    web:
        deploy:
            replicas: 0

networks:
    cafet_web:
        external: false

volumes:
    postgresql:
        name: "postgresql"
        external: false
